Feature: AMP Web Site MeetTheBand Page
  In order see what content the site has
  As a visitor to the site
  I need to have an MeetTheBand page
    
  Scenario: Manage Band Members
    Given I am on "/meettheband/"
    Then I should see 0 ".bandMemberEntry" elements
  	When I go to "meettheband/add"
  	Then I should be on "/login"
  	When I fill in "_username" with "admin"
  	And I fill in "_password" with "foo"
  	And I press "Login"
  	Then I should be on "meettheband/add"
    Then I should see a "form" element
    When I fill in "form_first_name" with "Action"
    And I fill in "form_last_name" with "Jackson"
    And I fill in "form_roles" with "Super Cop"
    And I fill in "form_bio" with "A celebrated lieutenant in the police force"
    And I press "Submit"
    Then I should be on "/meettheband/"
    And I should see "Action Jackson"
    And I should see "Super Cop"
    And I should see "A celebrated lieutenant in the police force"
    When I go to "/meettheband/add"
    When I fill in "form_first_name" with "Bilbo"
    And I fill in "form_last_name" with "Baggins"
    And I fill in "form_roles" with "Bravest Little Hobbit of Them All"
    And I press "Submit"
    Then I should be on "/meettheband/"
    And I should see "Bilbo Baggins"
    And I should see "Bravest Little Hobbit of Them All"
    When I press "Delete"
    Then I should not see "Action Jackson"
    When I follow "Logout"
    Then I should be on "/"
    When I go to "/meettheband/"
    Then I should not see "Add Band Member"
    And I should not see "Edit"
    And I should not see "Delete"
    When I go to "meettheband/update/2"
    Then I should be on "/login"
    When I fill in "_username" with "admin"
    And I fill in "_password" with "foo"
    And I press "Login"
    Then I should be on "meettheband/update/2"
    Then the "form_first_name" field should contain "Bilbo"
    Then the "form_last_name" field should contain "Baggins"
    Then the "form_roles" field should contain "Bravest Little Hobbit of Them All"
    When I fill in "form_roles" with "Professional Thief"
    And I press "Submit"
    Then I should be on "/meettheband/"
    And I should see "Bilbo Baggins"
    And I should see "Professional Thief"
    And I press "Delete"
    Then I should see 0 ".bandMemberEntry" elements
